// <auto-generated />
namespace OnlineExamManagementWebApp.DatabaseContext.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class changedcourseTrainerrelfromm2mto1tom : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changedcourseTrainerrelfromm2mto1tom));
        
        string IMigrationMetadata.Id
        {
            get { return "201809090453400_changed courseTrainer rel from m2m to 1tom"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
