// <auto-generated />
namespace OnlineExamManagementWebApp.DatabaseContext.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Added_NavigationProperty_CourseTrainer : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Added_NavigationProperty_CourseTrainer));
        
        string IMigrationMetadata.Id
        {
            get { return "201907100736454_Added_NavigationProperty_CourseTrainer"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
