// <auto-generated />
namespace OnlineExamManagementWebApp.DatabaseContext.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Add_OrderColumn_QuestionOption : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_OrderColumn_QuestionOption));
        
        string IMigrationMetadata.Id
        {
            get { return "202003231544305_Add_OrderColumn_QuestionOption"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
